"""optimizer/output_full.py — write the CP-SAT optimizer's committed month plan in
the SAME rich multi-sheet Excel format as the GREEDY engine.

Rather than re-implementing the greedy's sheet layouts, this module REUSES the greedy
engine's own two writer functions verbatim:

    b2c_pipeline._write_rolling_building_excel   -> building workbook
    b2c_pipeline._write_rolling_curing_excel     -> curing  workbook

We only translate the optimizer's month-global rows
(res['building_rows'] / res['curing_rows'], produced by optimizer.driver.run_rolling)
into the exact input structures those writers expect, then call them. So every sheet
(Shift Schedule, Changeover Plan, SKU Classification, Daily GT & Carcass,
Demand Fulfillment, Machine Utilization, Mould Tracker, Mould Movement, MouldInUse,
Machine Schedule, Daily Cured tyres, GT Gap Diagnostic) is generated by the *same*
code path that produces the greedy plan's workbooks — no divergence in columns/format.

What is REUSED-FROM-GREEDY (all of it): every sheet's layout, styling, KPI footer and
all derived aggregates (utilization %, demand fulfillment %, daily totals, SKU class).
What we SYNTHESIZE (data-prep only, not sheet logic): the per-shift CHANGEOVER sentinel
rows + CO-event lists, because the optimizer's committed-row export records only
production (machine/press -> SKU -> qty per shift), not explicit changeovers. We recover
a CO wherever a machine/press's SKU changes shift-to-shift (cost via the engine's own
_co_cost). Mould-mount tracking (Mould Tracker / Mould Movement / MouldInUse) is not
part of the optimizer's committed export, so mould_info is passed as None and those
sheets render the greedy writer's honest "no mould state / gate OFF" placeholder.
"""
from __future__ import annotations

import os
from datetime import timedelta

import pandas as pd

from b2c_pipeline import (
    _write_rolling_building_excel,
    _write_rolling_curing_excel,
    _co_cost,
    DEFAULT_CURING_CT,
    CURING_CAVITIES,
    CURING_CO_CHANGEOVER_MINS,
    MOULD_CLEAN_MINS,
)

_SHIFT_ORD = {"A": 0, "B": 1, "C": 2}
_SHIFT_START_HOUR = {"A": 7, "B": 15, "C": 23}          # plant shift clock
_GROUP_LABEL = {"S1": "Stage-1", "S2": "Stage-2", "UNI": "Unistage"}

# Display-only lever (env BLD_SHIFT_CO_WALLCLOCK, default ON): draw each building
# changeover in the Shift Schedule as an explicit wall-clock block at the head of the
# shift (StartTime .. StartTime+CO_Mins) with production following it, so the plant can
# read the same-size / diff-size CO time inline off the shift-wise timeline. Purely a
# rendering of the timestamps on the synthesized CHANGEOVER + production rows — it does
# NOT touch any quantity, KPI, CO count, or the Changeover Plan. BLD_SHIFT_CO_WALLCLOCK=0
# reproduces the prior sheet bit-for-bit (CO block zero-width at shift start; production
# spans the full shift). Same-size CO capacity is intentionally NOT charged to production
# (the model did not reserve it) — the window is shown for floor guidance only.
_BLD_SHIFT_CO_WALLCLOCK = os.environ.get("BLD_SHIFT_CO_WALLCLOCK", "1") != "0"


def _times(date_str: str, shift: str):
    """(StartTime, EndTime) strings 'YYYY-MM-DD HH:MM' for a full 480-min shift."""
    start = pd.Timestamp(date_str) + pd.Timedelta(hours=_SHIFT_START_HOUR.get(shift, 7))
    end = start + pd.Timedelta(minutes=480)
    return start.strftime("%Y-%m-%d %H:%M"), end.strftime("%Y-%m-%d %H:%M")


def _add_mins(dt_str: str, mins) -> str:
    """dt_str ('YYYY-MM-DD HH:MM') + mins -> same-format string. Used to draw a building
    CO block's wall-clock window (StartTime + CO_Mins)."""
    return (pd.Timestamp(dt_str) + pd.Timedelta(minutes=float(mins or 0))).strftime("%Y-%m-%d %H:%M")


def _sku_machine_map(mi) -> dict:
    """Invert mi.machine_allowed_skus -> {sku: set(building machines)} (GT + carcass)."""
    out: dict = {}
    for m, skus in mi.machine_allowed_skus.items():
        for s in skus:
            out.setdefault(s, set()).add(m)
    return out


def _build_df_day0(mi) -> pd.DataFrame:
    """Minimal SKU-classification frame the greedy writers read for Category/Priority.

    Category: RI = SKU running on a press at t0 (and in demand); NRI = in demand, not
    on any press. (RO never appears — the export is demand-filtered.)
    Priority_Score: the engine's v1 min-max of per-SKU demand (matches CLAUDE.md).
    """
    running = {s for s in mi.press_init_sku.values() if s}
    dem = mi.demand
    lo = min(dem.values()) if dem else 0
    hi = max(dem.values()) if dem else 0
    span = (hi - lo) or 1
    rows = []
    for s in mi.skus:
        rows.append({
            "SKUCode": s,
            "Category": "Runner-In" if s in running else "Non-Runner-In",
            "Demand_Qty": int(dem.get(s, 0)),
            "Priority_Score": (dem.get(s, 0) - lo) / span if hi > lo else 1.0,
        })
    return pd.DataFrame(rows)


def _building_inputs(res, mi):
    """Optimizer building_rows -> (bld_shift_rows, bld_co_events) the greedy writer reads."""
    rows = sorted(
        res.get("building_rows", []) or [],
        key=lambda r: (int(r["Day"]), _SHIFT_ORD.get(r["Shift"], 0),
                       str(r["Machine"]), str(r["SKUCode"])),
    )
    bld_shift_rows: list = []
    bld_co_events: list = []
    cur_sku: dict = {}          # machine -> last SKU produced (for CO detection)

    for r in rows:
        m = str(r["Machine"]); sku = str(r["SKUCode"]); shift = r["Shift"]
        date = r["Date"]; day = int(r["Day"])
        inch = str(r.get("Inch", ""))
        grp = _GROUP_LABEL.get(mi.machine_group.get(m, ""), r.get("Group", ""))
        typ = r.get("Type", "GT")
        st, et = _times(date, shift)

        prev = cur_sku.get(m)
        prod_start = st                       # where this shift's production begins
        if prev is not None and prev != sku:
            # SKU changed on this machine -> a changeover happened (same- or diff-size).
            from_inch = mi.sku_inch.get(prev, "")
            cost = _co_cost(m, from_inch, inch)
            co_type = "same_size_CO" if from_inch == inch else "diff_size_CO"
            # Wall-clock CO block at the head of the shift: st .. st+CO_Mins, with
            # production following (prod_start pushed past the block). Display-only;
            # BLD_SHIFT_CO_WALLCLOCK=0 restores the prior zero-width block at st and
            # full-shift production window (bit-for-bit).
            if _BLD_SHIFT_CO_WALLCLOCK:
                co_end = _add_mins(st, cost)
                prod_start = co_end
            else:
                co_end = st
            bld_shift_rows.append({
                "Machine": m, "Date": date, "Shift": shift, "SKUCode": "CHANGEOVER",
                "Qty": 0, "CO_Mins": cost, "StartTime": st, "EndTime": co_end,
                "Machine_Group": grp, "CO_Type": co_type,
            })
            bld_co_events.append({
                "Machine": m, "Date": date, "Day": day, "From_SKU": prev,
                "Target_SKU": sku, "CO_Type": co_type, "CO_Cost_Mins": cost,
                "CO_Day_Index": day, "Status": "DONE",
            })

        bld_shift_rows.append({
            "Machine": m, "Date": date, "Shift": shift, "SKUCode": sku,
            "Qty": int(r["Qty"]), "CO_Mins": 0, "StartTime": prod_start, "EndTime": et,
            "Machine_Group": grp, "CO_Type": "",
        })
        cur_sku[m] = sku

    return bld_shift_rows, bld_co_events


def _curing_inputs(res, mi, ct_map, clean_keys=None):
    """Optimizer curing_rows -> all the structures the greedy curing writer reads.

    Fix B: `clean_keys` is a set of (Date, Shift, Press) that a mould clean occupies. A
    matching per-shift row is marked MOULD_CLEAN (its production was already dropped to 0
    by the driver) and its 480-min clean is booked into press_stats['clean_mins'] so the
    Machine Utilization occupancy and Shift Schedule reflect the clean.
    """
    from collections import defaultdict

    clean_keys = clean_keys or set()
    rows = sorted(
        res.get("curing_rows", []) or [],
        key=lambda r: (int(r["Day"]), _SHIFT_ORD.get(r["Shift"], 0),
                       str(r["Press"]), str(r["SKUCode"])),
    )

    cure_shift_rows: list = []
    cure_co_events: list = []
    press_stats: dict = defaultdict(lambda: {"running_mins": 0.0, "co_mins": 0.0,
                                             "clean_mins": 0.0, "skus": set(),
                                             "cycles": 0, "units": 0})
    press_sku_stats: dict = defaultdict(lambda: {"cycles": 0, "units": 0, "mins_used": 0.0})
    daily_cured: dict = defaultdict(int)
    sku_cured: dict = defaultdict(int)
    build_by_shift_sku: dict = defaultdict(lambda: defaultdict(int))
    cur_sku: dict = {}          # press -> last SKU (for CO detection)

    for r in rows:
        p = str(r["Press"]); sku = str(r["SKUCode"]); shift = r["Shift"]
        date = r["Date"]; day = int(r["Day"]); qty = int(r["Qty"])
        ct = ct_map.get(sku, DEFAULT_CURING_CT)
        st, et = _times(date, shift)

        prev = cur_sku.get(p)
        if prev is not None and prev != sku:
            cure_shift_rows.append({
                "Date": date, "Shift": shift, "Machine": p, "SKUCode": "CHANGEOVER",
                "StartTime": st, "EndTime": et, "Qty": 0,
                "CO_Mins": CURING_CO_CHANGEOVER_MINS, "Mould_Clean_Mins": 0,
                "CycleTime_min": round(ct, 2), "GT_Inventory": "",
                "Remarks": f"CO {prev}->{sku}", "_status": "CHANGEOVER",
            })
            cure_co_events.append({
                "Date": date, "Day": day, "Shift": shift, "Press": p,
                "From_SKU": prev, "Target_SKU": sku, "CO_Type": "Planned",
                "Mins": CURING_CO_CHANGEOVER_MINS,
            })
            press_stats[p]["co_mins"] += CURING_CO_CHANGEOVER_MINS

        _is_clean = (date, shift, p) in clean_keys
        cure_shift_rows.append({
            "Date": date, "Shift": shift, "Machine": p, "SKUCode": sku,
            "StartTime": st, "EndTime": et, "Qty": qty, "CO_Mins": 0,
            "Mould_Clean_Mins": (MOULD_CLEAN_MINS if _is_clean else 0),
            "CycleTime_min": round(ct, 2),
            "GT_Inventory": "", "Remarks": ("Mould Clean" if _is_clean else ""),
            "_status": ("MOULD_CLEAN" if _is_clean else "RUNNING"),
        })

        cycles = qty // CURING_CAVITIES
        mins = cycles * ct
        ps = press_stats[p]
        ps["running_mins"] += mins; ps["units"] += qty; ps["cycles"] += cycles
        if _is_clean:
            ps["clean_mins"] += MOULD_CLEAN_MINS
        ps["skus"].add(sku)
        pk = press_sku_stats[(p, sku)]
        pk["units"] += qty; pk["cycles"] += cycles; pk["mins_used"] += mins
        daily_cured[date] += qty
        sku_cured[sku] += qty
        cur_sku[p] = sku

    # GT built per (date,shift) per SKU — for the GT Gap Diagnostic sheet.
    for r in (res.get("building_rows", []) or []):
        if r.get("Type") == "GT":
            build_by_shift_sku[(r["Date"], r["Shift"])][str(r["SKUCode"])] += int(r["Qty"])

    # Closing GT balance = built(GT) + opening - cured, clipped at 0.
    built_gt: dict = defaultdict(float)
    for r in (res.get("building_rows", []) or []):
        if r.get("Type") == "GT":
            built_gt[str(r["SKUCode"])] += float(r["Qty"])
    closing_gt_bal: dict = {}
    for s in mi.skus:
        bal = built_gt.get(s, 0.0) + float(mi.opening_gt.get(s, 0)) - float(sku_cured.get(s, 0))
        closing_gt_bal[s] = max(0.0, bal)

    return (cure_shift_rows, cure_co_events, dict(press_stats), dict(press_sku_stats),
            dict(daily_cured), dict(sku_cured), closing_gt_bal, build_by_shift_sku)


def _build_mould_info(res, mi):
    """Fix D — assemble the greedy writer's `mould_info` from the optimizer's recovered
    per-shift press->mould mounts (res['mould_rows']). Feeds the Mould Tracker (one row
    per press×mould×SKU-run), Mould Movement (one row per swap) and MouldInUse sheets.

    Returns the mould_info dict, or None if there is no mould-mount data.
    """
    from collections import defaultdict

    rows = res.get("mould_rows") or []
    if not rows:
        return None

    sku_moulds = {s: set(str(m) for m in v) for s, v in mi.sku_moulds.items()}
    mould_skus: dict = defaultdict(set)
    for s, ms in sku_moulds.items():
        for m in ms:
            mould_skus[m].add(s)

    rows = sorted(rows, key=lambda r: (int(r["Day"]), _SHIFT_ORD.get(r["Shift"], 0),
                                       str(r["Press"])))
    by_press: dict = defaultdict(list)
    for r in rows:
        by_press[str(r["Press"])].append(r)

    assignments: list = []
    events: list = []
    press_moulds: dict = {}
    final_sku: dict = {}
    press_count: dict = defaultdict(set)

    for press, prs in sorted(by_press.items()):
        cur_run = None
        mounted: set = set()                      # moulds physically on the press now
        for r in prs:
            sku = str(r["SKUCode"]); day = int(r["Day"])
            moulds = [str(m) for m in (r.get("Moulds") or [])]
            press_count[sku].add(press)
            if cur_run is None or cur_run["sku"] != sku:
                if cur_run is not None:
                    assignments.append(cur_run)
                cur_run = {"press": press, "sku": sku, "day": day, "moulds": set(moulds)}
                newset = set(moulds)
                if newset and newset != mounted:  # a real mould swap
                    events.append({
                        "day": day, "press": press, "sku": sku,
                        "added": sorted(newset - mounted),
                        "removed": sorted(mounted - newset),
                    })
                    mounted = newset
            else:
                cur_run["moulds"].update(moulds)
                if moulds:
                    mounted |= set(moulds)
            final_sku[press] = sku
        if cur_run is not None:
            assignments.append(cur_run)
        press_moulds[press] = sorted(mounted)

    # normalise assignment moulds to sorted lists
    for a in assignments:
        a["moulds"] = sorted(a["moulds"])

    return {
        "press_moulds": press_moulds,
        "final_sku":    final_sku,
        "mould_skus":   {m: set(s) for m, s in mould_skus.items()},
        "sku_moulds":   sku_moulds,
        "press_count":  {s: len(ps) for s, ps in press_count.items()},
        "blocked":      0,
        "retargeted":   0,
        "day0_topups":  0,
        "scorer":       None,
        "events":       events,
        "assignments":  assignments,
    }


def write_full_schedules(res, mi, ct_map=None, out_dir="main_output", demand_path=None):
    """Write the optimizer plan to `out_dir` in the full greedy multi-sheet format.

    Returns {'building': path, 'curing': path}. Reuses the greedy writers verbatim.
    """
    os.makedirs(out_dir, exist_ok=True)
    stamp = mi.plan_start.strftime("%Y-%m-%d")
    ct_map = ct_map or {}

    sku_mm = _sku_machine_map(mi)
    curing_allowable = {s: list(ps) for s, ps in mi.sku_presses.items()}
    df_day0 = _build_df_day0(mi)

    # Fix C: per-committed-day end-of-day GT reservoir (None when OPT_ENDDAY_GT=0).
    endday_gt_by_date = res.get("endday_gt_by_date")
    # Fix B: mould-clean events + final decremented mould life ([]/{} when OPT_MOULD_CLEAN=0).
    mould_clean_events = list(res.get("mould_clean_events") or [])
    clean_keys = {(str(e["Date"]), str(e["Shift"]), str(e["Press"]))
                  for e in mould_clean_events}
    mould_life_out = res.get("final_mould_life") or dict(mi.mould_life)
    # Fix D: per-shift mould mounts -> mould_info (None when OPT_MOULD_INFO=0 -> no rows).
    mould_info = _build_mould_info(res, mi)

    # ---- BUILDING ----
    bld_shift_rows, bld_co_events = _building_inputs(res, mi)
    bld_path = os.path.join(out_dir, f"optimizer_building_schedule_full_{stamp}.xlsx")
    _write_rolling_building_excel(
        output_path=bld_path,
        bld_shift_rows=bld_shift_rows,
        bld_co_events=bld_co_events,
        df_day0=df_day0,
        sku_machine_map=sku_mm,
        opening_gt=dict(mi.opening_gt),
        demand_dict=dict(mi.demand),
        planning_days=int(mi.planning_days),
        n_curing_cos=_count_curing_cos(res),
        endday_gt_by_date=endday_gt_by_date,
        cure_ct_map=ct_map,
        curing_allowable=curing_allowable,
        sku_moulds={s: set(v) for s, v in mi.sku_moulds.items()},
    )

    # ---- CURING ----
    (cure_shift_rows, cure_co_events, press_stats, press_sku_stats, daily_cured,
     sku_cured, closing_gt_bal, build_by_shift_sku) = _curing_inputs(
        res, mi, ct_map, clean_keys=clean_keys)

    sku_desc_map = None
    if demand_path:
        try:
            from b2c_pipeline import _build_sku_desc_map
            sku_desc_map = _build_sku_desc_map(demand_path)
        except Exception:
            sku_desc_map = None

    cur_path = os.path.join(out_dir, f"optimizer_curing_schedule_full_{stamp}.xlsx")
    _write_rolling_curing_excel(
        output_path=cur_path,
        cure_shift_rows=cure_shift_rows,
        cure_co_events=cure_co_events,
        mould_clean_events=mould_clean_events,   # Fix B
        press_stats=press_stats,
        press_sku_stats=press_sku_stats,
        daily_cured=daily_cured,
        sku_cured=sku_cured,
        closing_gt_bal=closing_gt_bal,
        build_by_shift_sku=build_by_shift_sku,
        opening_gt=dict(mi.opening_gt),
        demand_dict=dict(mi.demand),
        cure_ct_map=ct_map,
        curing_allowable=curing_allowable,
        planning_days=int(mi.planning_days),
        plan_start=mi.plan_start,
        df_day0=df_day0,
        mould_life=mould_life_out,               # Fix B: final decremented life
        mould_info=mould_info,                    # Fix D: recovered mould mounts
        sku_desc_map=sku_desc_map,
        sku_machine_map=sku_mm,
    )

    return {"building": bld_path, "curing": cur_path,
            "n_building_rows": len(bld_shift_rows),
            "n_curing_rows": len(cure_shift_rows),
            "n_building_cos": len(bld_co_events),
            "n_curing_cos": len(cure_co_events)}


def _count_curing_cos(res):
    """Curing CO count = press SKU-changes shift-to-shift (for the building KPI footer)."""
    from collections import defaultdict
    rows = sorted(
        res.get("curing_rows", []) or [],
        key=lambda r: (int(r["Day"]), _SHIFT_ORD.get(r["Shift"], 0), str(r["Press"])),
    )
    cur: dict = {}
    n = 0
    for r in rows:
        p = str(r["Press"]); sku = str(r["SKUCode"])
        if cur.get(p) is not None and cur[p] != sku:
            n += 1
        cur[p] = sku
    return n
